### ISSUE TITLE
Server crash after map change BMS windows

### ISSUE THREAD

**Issue by yurakone** [Alienmario/ModelChooser#2]
`1/ - player:  UTIL_SetModel:  not precached: models\player\mp_scientist_hev.mdl`
```
Listing 4 plugins:
  [01] SourceMod (1.10.0.6528) by AlliedModders LLC
  [02] SDK Tools (1.10.0.6528) by AlliedModders LLC
  [03] DHooks (1.11.0.6887) by AlliedModders LLC
  [04] SDK Hooks (1.10.0.6528) by AlliedModders LLC
```
HL2DM with same configuration works well

**Comment by yurakone** [comment]
Built-in models are not precached, but plugin works well if use only custom downloadable models

**Comment by Alienmario** [comment]
That's weird, I ran this without issue in BM. I'll test it later. Are you running a typical DM server?

**Comment by yurakone** [comment]
Yes, SteamCmd Black Mesa Dedicated Server, tested on two different servers, same problem. 
UPD. No matter which model, custom models cause error also, after map change
`1/ - player:  UTIL_SetModel:  not precached: models\memes\dr_m_freeman.mdl`

**Comment by Alienmario** [comment]
Couldn't replicate it. It seems they precache fine for me.

**Comment by yurakone** [comment]
> Couldn't replicate it. It seems they precache fine for me.
Idk, maybe because windows, as far as I understand windows isn't best srcds platform
https://user-images.githubusercontent.com/98318619/172492957-e712f2b8-72eb-420e-a924-2ffe1911d672.MOV

**Comment by Alienmario** [comment]
I'm on windows as well. I see you have SourceTV enabled, can you try without it?

**Comment by yurakone** [comment]
Yes, seems the source tv incompatible with the plugin in the BMS. It is possible to make work it together? 
HL2DM works perfectly. btw thanks, great plugin!

**Comment by Alienmario** [comment]
Yes but you will have to compile it yourself as I don't use 1.10 anymore.
