### ISSUE TITLE
SourceTV+ModelChooser

### ISSUE THREAD

**Issue by yurakone** [Alienmario/ModelChooser#5]
[HL2DM] SourceTV `tv_record` or `tv_autorecord`  demo records  are corrupted and cause crash when trying to playback.
[BMS] Causes server crash on map change if  `tv_autorecord 1`

**Comment by Alienmario** [comment]
Ok, I'll backport my private version, which is further developed with fixes and features. Hopefully that solves it.

**Comment by Alienmario** [comment]
Confirmed as fixed.
